### ISSUE TITLE
使用时报错。

### ISSUE THREAD

**Issue by 0x5010** [sylnsfar/qrcode#1]
python myqr.py http://weixin.qq.com/r/PUgrM0TEzBmzrQBQ9xxx -p aaa.jpg
```
Traceback (most recent call last):
  File "myqr.py", line 72, in <module>
    ver, qr_name = theqrmodule.get_qrcode(ver, ecl, args.WORDs, save_place)
  File "/xxxx/qrcode-master/mylibs/theqrmodule.py", line 29, in get_qrcode
    qrmatrix = matrix.get_qrmatrix(ver, ecl, final_bits)
  File "/xxxx/qrcode-master/mylibs/matrix.py", line 45, in get_qrmatrix
    place_bits(bits, qrmatrix)
  File "/xxxx/qrcode-master/mylibs/matrix.py", line 106, in place_bits
    m[i][j] = next(bit)
StopIteration
```
微信链接有问题.

**Comment by sylnsfar** [comment]
现在修复了，你试一下。
