### ISSUE TITLE
Artistic QR-Code

### ISSUE THREAD

**Issue by NoWayBg** [sylnsfar/qrcode#39]
About Artistic QR-Code I can't make QR code combine with an image.
A error mess is displayed : 
"Traceback (most recent call last):
  File "C:\Python36\Scripts\myqr-script.py", line 11, in <module>
    load_entry_point('MyQR==2.3.1', 'console_scripts', 'myqr')()
  File "c:\python36\lib\site-packages\MyQR\terminal.py", line 34, in main
    args.directory
  File "c:\python36\lib\site-packages\MyQR\myqr.py", line 36, in run
    raise ValueError("Wrong picture! Input a filename that exists and be tailed with one of {'.jpg', '.png', '.bmp', '
}!")
ValueError: Wrong picture! Input a filename that exists and be tailed with one of {'.jpg', '.png', '.bmp', '.gif'}!"
So can you tell me where I should put an image to make QR code.
Thank you so much.

**Comment by ztickm** [comment]
the command should be like this `myqr [stuff you want to encode] -p [path/to/your/image]`
Although I'm not sure how it handles windows paths.
Also, your image must end in either .jpg, .png, .bmp, or .gif
