### ISSUE TITLE
When I use the -p option,it raise a problem

### ISSUE THREAD

**Issue by yansheng836** [sylnsfar/qrcode#54]
I have install the tool with pip,and this command ` myqr https://github.com` will work. But when I use the `-p` option it will raise a error , a litter this issue https://github.com/sylnsfar/qrcode/issues/39#issue-342540639.

The detailed error information is as follows：
```bash
# 1. using -p
$ myqr https://github.com -p github.jpg
Traceback (most recent call last):
  File "G:\python-3.7.1\Scripts\myqr-script.py", line 11, in <module>
    load_entry_point('MyQR==2.3.1', 'console_scripts', 'myqr')()
  File "g:\python-3.7.1\lib\site-packages\MyQR\terminal.py", line 34, in main
    args.directory
  File "g:\python-3.7.1\lib\site-packages\MyQR\myqr.py", line 36, in run
    raise ValueError("Wrong picture! Input a filename that exists and be tailed with one of {'.jpg', '.png', '.bmp', '.gif'}!")
ValueError: Wrong picture! Input a filename that exists and be tailed with one of {'.jpg', '.png', '.bmp', '.gif'}!


# 2 using -p -c
$ myqr https://github.com -p github.jpg -c
Traceback (most recent call last):
  File "G:\python-3.7.1\Scripts\myqr-script.py", line 11, in <module>
    load_entry_point('MyQR==2.3.1', 'console_scripts', 'myqr')()
  File "g:\python-3.7.1\lib\site-packages\MyQR\terminal.py", line 34, in main
    args.directory
  File "g:\python-3.7.1\lib\site-packages\MyQR\myqr.py", line 36, in run
    raise ValueError("Wrong picture! Input a filename that exists and be tailed with one of {'.jpg', '.png', '.bmp', '.gif'}!")
ValueError: Wrong picture! Input a filename that exists and be tailed with one of {'.jpg', '.png', '.bmp', '.gif'}!

``` 

I think the option `-p` has some problem.

**Comment by yansheng836** [comment]
I think it's my problem. I didn't understand the instructions at the beginning. I'm sorry.
